"""Core schema: clients, documents, tasks, audit log, ledger, knowledge store, model calls.

Integrity rules live in the database so no application bug can bypass them:
- the audit log and the ledger are append-only;
- every journal entry balances when its transaction commits;
- every task change sends NOTIFY task_events (delivered only on commit).

Revision ID: 0002
Revises: 0001
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TASK_STATES = (
    "queued",
    "processing",
    "auto_approved",
    "needs_review",
    "approved",
    "blocked",
    "rejected",
    "failed",
    "posted",
)

INTEGRITY_SQL = [
    # Audit log: append-only.
    """
    CREATE FUNCTION reject_modification() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
    END $$
    """,
    """CREATE TRIGGER audit_log_append_only BEFORE UPDATE OR DELETE ON audit_log
       FOR EACH ROW EXECUTE FUNCTION reject_modification()""",
    """CREATE TRIGGER audit_log_no_truncate BEFORE TRUNCATE ON audit_log
       FOR EACH STATEMENT EXECUTE FUNCTION reject_modification()""",
    # Ledger: posted entries are never edited; corrections are reversing entries.
    """CREATE TRIGGER journal_entries_append_only BEFORE UPDATE OR DELETE ON journal_entries
       FOR EACH ROW EXECUTE FUNCTION reject_modification()""",
    """CREATE TRIGGER journal_lines_append_only BEFORE UPDATE OR DELETE ON journal_lines
       FOR EACH ROW EXECUTE FUNCTION reject_modification()""",
    """ALTER TABLE journal_lines ADD CONSTRAINT journal_lines_one_side
       CHECK (debit >= 0 AND credit >= 0 AND (debit > 0) <> (credit > 0))""",
    # Every entry balances when the transaction commits.
    """
    CREATE FUNCTION check_entry_balances() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE
        debits numeric;
        credits numeric;
    BEGIN
        SELECT COALESCE(sum(debit), 0), COALESCE(sum(credit), 0) INTO debits, credits
        FROM journal_lines WHERE entry_id = NEW.entry_id;
        IF debits <> credits THEN
            RAISE EXCEPTION 'journal entry % does not balance: debits % <> credits %',
                NEW.entry_id, debits, credits;
        END IF;
        RETURN NULL;
    END $$
    """,
    """CREATE CONSTRAINT TRIGGER journal_lines_balance AFTER INSERT ON journal_lines
       DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION check_entry_balances()""",
    # Task states are the lifecycle's states only.
    "ALTER TABLE tasks ADD CONSTRAINT tasks_state_valid CHECK (state IN ("
    + ", ".join(f"'{s}'" for s in TASK_STATES)
    + "))",
    # Real-time: every task change is announced (NOTIFY is delivered on commit only).
    """
    CREATE FUNCTION notify_task_change() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
        PERFORM pg_notify('task_events', json_build_object(
            'task_id', NEW.id, 'client_id', NEW.client_id, 'state', NEW.state,
            'updated_at', NEW.updated_at)::text);
        RETURN NULL;
    END $$
    """,
    """CREATE TRIGGER tasks_notify AFTER INSERT OR UPDATE ON tasks
       FOR EACH ROW EXECUTE FUNCTION notify_task_change()""",
]

DROP_INTEGRITY_SQL = [
    "DROP TRIGGER IF EXISTS tasks_notify ON tasks",
    "DROP FUNCTION IF EXISTS notify_task_change()",
    "DROP TRIGGER IF EXISTS journal_lines_balance ON journal_lines",
    "DROP FUNCTION IF EXISTS check_entry_balances()",
    "DROP TRIGGER IF EXISTS journal_lines_append_only ON journal_lines",
    "DROP TRIGGER IF EXISTS journal_entries_append_only ON journal_entries",
    "DROP TRIGGER IF EXISTS audit_log_no_truncate ON audit_log",
    "DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log",
    "DROP FUNCTION IF EXISTS reject_modification()",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("business", sa.Text(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "accounts",
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("capitalizable", sa.Boolean(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("client_id", "code"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("media_type", sa.String(length=32), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("content", sa.LargeBinary(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("doc_type", sa.String(length=16), nullable=True),
        sa.Column("extracted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("vendor_key", sa.Text(), nullable=True),
        sa.Column("number_key", sa.Text(), nullable=True),
        sa.Column("reference_key", sa.Text(), nullable=True),
        sa.Column("total", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_client_id"), "documents", ["client_id"], unique=False)
    op.create_index(op.f("ix_documents_sha256"), "documents", ["sha256"], unique=False)
    op.create_index(op.f("ix_documents_vendor_key"), "documents", ["vendor_key"], unique=False)
    op.create_table(
        "knowledge_entries",
        sa.Column("id", sa.String(length=96), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("vendor_key", sa.Text(), nullable=False),
        sa.Column("vendor_name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("account", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("document_ref", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(384), nullable=False),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', vendor_name || ' ' || description)", persisted=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("seq"),
    )
    op.create_index(
        op.f("ix_knowledge_entries_client_id"), "knowledge_entries", ["client_id"], unique=False
    )
    op.create_index(
        "ix_knowledge_entries_tsv",
        "knowledge_entries",
        ["tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_knowledge_entries_vendor_trgm",
        "knowledge_entries",
        ["vendor_key"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"vendor_key": "gin_trgm_ops"},
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("state_entered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assignee_id", sa.String(length=64), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("extraction", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("coding", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("routing", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("line_accounts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id"),
    )
    op.create_index(op.f("ix_tasks_client_id"), "tasks", ["client_id"], unique=False)
    op.create_index(op.f("ix_tasks_state"), "tasks", ["state"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("actor_kind", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("from_state", sa.String(length=16), nullable=True),
        sa.Column("to_state", sa.String(length=16), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "seq"),
    )
    op.create_index(op.f("ix_audit_log_task_id"), "audit_log", ["task_id"], unique=False)
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=False),
        sa.Column("reverses", sa.String(length=64), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reverses"],
            ["journal_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_journal_entries_client_id"), "journal_entries", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entries_task_id"), "journal_entries", ["task_id"], unique=False
    )
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("request_key", sa.String(length=64), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("replayed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_calls_task_id"), "llm_calls", ["task_id"], unique=False)
    op.create_table(
        "journal_lines",
        sa.Column("entry_id", sa.String(length=64), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("account_code", sa.String(length=16), nullable=False),
        sa.Column("debit", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("credit", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("memo", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["journal_entries.id"],
        ),
        sa.PrimaryKeyConstraint("entry_id", "line_no"),
    )
    # ### end Alembic commands ###
    for statement in INTEGRITY_SQL:
        op.execute(statement)


def downgrade() -> None:
    for statement in DROP_INTEGRITY_SQL:
        op.execute(statement)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("journal_lines")
    op.drop_index(op.f("ix_llm_calls_task_id"), table_name="llm_calls")
    op.drop_table("llm_calls")
    op.drop_index(op.f("ix_journal_entries_task_id"), table_name="journal_entries")
    op.drop_index(op.f("ix_journal_entries_client_id"), table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index(op.f("ix_audit_log_task_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_tasks_state"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_client_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(
        "ix_knowledge_entries_vendor_trgm",
        table_name="knowledge_entries",
        postgresql_using="gin",
        postgresql_ops={"vendor_key": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_knowledge_entries_tsv", table_name="knowledge_entries", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_knowledge_entries_client_id"), table_name="knowledge_entries")
    op.drop_table("knowledge_entries")
    op.drop_index(op.f("ix_documents_vendor_key"), table_name="documents")
    op.drop_index(op.f("ix_documents_sha256"), table_name="documents")
    op.drop_index(op.f("ix_documents_client_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_table("accounts")
    op.drop_table("users")
    op.drop_table("clients")
    # ### end Alembic commands ###
